spring:
  datasource:
    url: jdbc:mysql://192.168.84.50:3306/jpa
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
#      更新或创建数据表
      ddl-auto: update
#    控制台显示SQL
    show-sql: true